name: nivalta

volumes:
 authdb_vol:
 uploadsdb_vol:
 ocrdb_vol:
 vectordb_vol:
 chatdb_vol:
 pages_vol:
 uploads_vol:

networks:
 auth-network:
   driver: bridge
 uploads-network:
   driver: bridge
 ocr-network:
   driver: bridge
 vector-network:
   driver: bridge
 chat-network:
   driver: bridge
 nivalta-network:
   driver: bridge

services:
  authentication-api:
    container_name: cauthentication
    build:
      context: ./python/authentication
    depends_on:
      local-auth-db:
        condition: service_healthy
    networks:
      - auth-network
      - nivalta-network
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./python/authentication:/usr/src/authentication:delegated
    # restart: always

  uploads-api:
    container_name: cuploads
    build:
      context: ./python/uploads
    depends_on:
      local-uploads-db:
        condition: service_healthy
    networks:
      - uploads-network
      - nivalta-network
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "5001:5001"
    volumes:
      - ./python/uploads:/usr/src/uploads:delegated
      - uploads_vol:/usr/src/uploads/uploads
    restart: always

  ocr-api:
    container_name: cocr
    build:
      context: ./python/ocr
    depends_on:
      local-ocr-db:
        condition: service_healthy
    networks:
      - ocr-network
      - nivalta-network
    ports:
      - "5002:5002"
    volumes:
      - ./python/ocr:/usr/src/ocr-service:delegated
      - ~/.aws/credentials.tmp:/home/appuser/.aws/credentials
      - pages_vol:/usr/src/ocr-service/pages
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - AWS_PROFILE=local-containers
    restart: always

  vector-api:
    container_name: cvector
    build:
      context: ./python/vector_db
    restart: always
    networks:
      - vector-network
      - nivalta-network
    ports:
      - "5003:5003"
    volumes:
      - ./python/vector_db:/usr/src/vector_db:delegated
    environment:
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      local-vector-db:
        condition: service_healthy

  chat-api:
    container_name: cchat
    build:
      context: ./python/chat
    restart: always
    networks:
      - chat-network
      - nivalta-network
    ports:
      - "5004:5004"
    volumes:
      - ./python/chat:/usr/src/chat:delegated
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://local_chat_user:local_chat_pass@local-chat-db:5432/chat_db
      - VECTOR_API_URL=http://vector-api:5003
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      local-chat-db:
        condition: service_healthy

  react-ui:
    container_name: creact
    build:
      context: ./react
    networks:
      - nivalta-network
    ports:
      - "8080:8080"
    volumes:
      - ./react/src:/usr/src/react/src
      - ./react/public:/usr/src/react/public
      - ./react/vite.config.js:/usr/src/react/vite.config.js
      - ./react/tailwind.config.js:/usr/src/react/tailwind.config.js
      - ./react/postcss.config.js:/usr/src/react/postcss.config.js
      - ./react/index.html:/usr/src/react/index.html
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - PROD=false
    restart: always

  nginx-proxy:
    container_name: cnginx
    build:
      context: ./nginx
    networks:
      - nivalta-network
    ports:
      - "80:80"
    environment:
      - AUTHENTICATION_SERVICE_HOST=authentication-api
      - OCR_SERVICE_HOST=ocr-api
      - UPLOADS_HOST=uploads-api
      - REACT_SERVICE_HOST=react-ui
      - VECTOR_SERVICE_HOST=vector-api
      - CHAT_SERVICE_HOST=chat-api  
    restart: always
    depends_on:
      - authentication-api
      - ocr-api
      - uploads-api
      - react-ui
      - vector-api
      - chat-api

  local-auth-db:
    container_name: clocal-auth-dbase
    image: mysql:8
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_auth_pass
      MYSQL_DATABASE: auth
      MYSQL_USER: local_auth_user
      MYSQL_PASSWORD: local_auth_pass
    networks:
      - auth-network
    volumes:
      - authdb_vol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  local-ocr-db:
    container_name: clocal-ocr-dbase
    image: postgres:15
    ports:
      - "32002:5432"
    environment:
      POSTGRES_DB: ocr_db
      POSTGRES_USER: local_ocr_user
      POSTGRES_PASSWORD: local_ocr_pass
    networks:
      - ocr-network
    volumes:
      - ocrdb_vol:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  local-uploads-db:
    container_name: clocal-uploads-dbase
    image: mysql:8
    ports:
      - "32001:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root_uploads_pass
      MYSQL_DATABASE: uploads_db
      MYSQL_USER: local_uploads_user
      MYSQL_PASSWORD: local_uploads_pass
    networks:
      - uploads-network
    volumes:
      - uploadsdb_vol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  local-vector-db:
    container_name: clocal-vector-dbase
    image: ankane/pgvector
    ports:
      - "32003:5432"
    environment:
      POSTGRES_DB: local_vector_db
      POSTGRES_USER: local_vector_user
      POSTGRES_PASSWORD: local_vector_pass
    networks:
      - vector-network
    volumes:
      - vectordb_vol:/var/lib/postgresql/data
      - ./python/vector_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  local-chat-db:
    container_name: clocal-chat-dbase
    image: postgres:15
    ports:
      - "32004:5432"
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: local_chat_user
      POSTGRES_PASSWORD: local_chat_pass
    networks:
      - chat-network
    volumes:
      - chatdb_vol:/var/lib/postgresql/data
      - ./python/chat/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5