AWSTemplateFormatVersion: '2010-09-09'
Description: Nivalta Services Stack
Parameters:
  Environment:
    Type: String
    AllowedValues:
    - prod
    - preprod
  ECSCluster:
    Type: String
    Description: Name of the ECS Cluster
  PublicSubnetOne:
    Type: AWS::EC2::Subnet::Id
  PublicSubnetTwo:
    Type: AWS::EC2::Subnet::Id
  TaskDefinitionsStackName:
    Type: String
  ServiceDiscoveryStackName:
    Type: String
  SecurityGroupsStackName:
    Type: String
Resources:
  FlaskService:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/e9b79b74cd1d8f69041ab7d12f46fb0f.template
      Parameters:
        Environment:
          Ref: Environment
        ECSCluster:
          Ref: ECSCluster
        PublicSubnetOne:
          Ref: PublicSubnetOne
        PublicSubnetTwo:
          Ref: PublicSubnetTwo
        TaskDefinitionsStackName:
          Ref: TaskDefinitionsStackName
        ServiceDiscoveryStackName:
          Ref: ServiceDiscoveryStackName
        SecurityGroupsStackName:
          Ref: SecurityGroupsStackName
  SveltekitService:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/15190ea9706549cfd23be979c54f6620.template
      Parameters:
        Environment:
          Ref: Environment
        ECSCluster:
          Ref: ECSCluster
        PublicSubnetOne:
          Ref: PublicSubnetOne
        PublicSubnetTwo:
          Ref: PublicSubnetTwo
        TaskDefinitionsStackName:
          Ref: TaskDefinitionsStackName
        ServiceDiscoveryStackName:
          Ref: ServiceDiscoveryStackName
        SecurityGroupsStackName:
          Ref: SecurityGroupsStackName
Outputs:
  FlaskServiceArn:
    Value:
      Fn::GetAtt:
      - FlaskService
      - Outputs.ServiceArn
  SveltekitServiceArn:
    Value:
      Fn::GetAtt:
      - SveltekitService
      - Outputs.ServiceArn
