AWSTemplateFormatVersion: '2010-09-09'
Description: Nivalta Services Stack
Parameters:
  Environment:
    Type: String
    AllowedValues:
    - prod
    - preprod
  ECSCluster:
    Type: String
    Description: Name of the ECS Cluster
  PublicSubnetOne:
    Type: AWS::EC2::Subnet::Id
  PublicSubnetTwo:
    Type: AWS::EC2::Subnet::Id
  TaskDefinitionsStackName:
    Type: String
  ServiceDiscoveryStackName:
    Type: String
  SecurityGroupsStackName:
    Type: String
  LoadBalancerStackName:
    Type: String
Resources:
  FlaskService:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/23951744e177ec0e7b4658b53884ebba.template
      Parameters:
        Environment:
          Ref: Environment
        ECSCluster:
          Ref: ECSCluster
        PublicSubnetOne:
          Ref: PublicSubnetOne
        PublicSubnetTwo:
          Ref: PublicSubnetTwo
        TaskDefinitionsStackName:
          Ref: TaskDefinitionsStackName
        ServiceDiscoveryStackName:
          Ref: ServiceDiscoveryStackName
        SecurityGroupsStackName:
          Ref: SecurityGroupsStackName
  SveltekitService:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/85223c738f7ad50973b8edb0c7f4fb2d.template
      Parameters:
        Environment:
          Ref: Environment
        ECSCluster:
          Ref: ECSCluster
        PublicSubnetOne:
          Ref: PublicSubnetOne
        PublicSubnetTwo:
          Ref: PublicSubnetTwo
        TaskDefinitionsStackName:
          Ref: TaskDefinitionsStackName
        ServiceDiscoveryStackName:
          Ref: ServiceDiscoveryStackName
        SecurityGroupsStackName:
          Ref: SecurityGroupsStackName
  NginxService:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - FlaskService
    - SveltekitService
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/a852794a677d86bddf141dee0f6786ea.template
      Parameters:
        Environment:
          Ref: Environment
        ECSCluster:
          Ref: ECSCluster
        PublicSubnetOne:
          Ref: PublicSubnetOne
        PublicSubnetTwo:
          Ref: PublicSubnetTwo
        TaskDefinitionsStackName:
          Ref: TaskDefinitionsStackName
        ServiceDiscoveryStackName:
          Ref: ServiceDiscoveryStackName
        SecurityGroupsStackName:
          Ref: SecurityGroupsStackName
        LoadBalancerStackName:
          Ref: LoadBalancerStackName
Outputs:
  NginxServiceArn:
    Value:
      Fn::GetAtt:
      - NginxService
      - Outputs.ServiceArn
  FlaskServiceArn:
    Value:
      Fn::GetAtt:
      - FlaskService
      - Outputs.ServiceArn
  SveltekitServiceArn:
    Value:
      Fn::GetAtt:
      - SveltekitService
      - Outputs.ServiceArn
