AWSTemplateFormatVersion: '2010-09-09'
Description: Nivalta Services Stack
Parameters:
  Environment:
    Type: String
    AllowedValues:
    - prod
    - preprod
  ECSCluster:
    Type: String
    Description: Name of the ECS Cluster
  PublicSubnetOne:
    Type: AWS::EC2::Subnet::Id
  PublicSubnetTwo:
    Type: AWS::EC2::Subnet::Id
  TaskDefinitionsStackName:
    Type: String
    Description: Name of the Task Definitions Stack
  FlaskTaskDefinitionARN:
    Type: String
  SveltekitTakDefinitionARN:
    Type: String
  FlaskServiceDiscoveryARN:
    Type: String
  SveltekitServiceDiscoveryARN:
    Type: String
  FlaskSecurityGroupId:
    Type: String
  SveltekitSecurityGroupId:
    Type: String
Resources:
  FlaskService:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/08252f0f38ecb9f81828084d2bd4159b.template
      Parameters:
        Environment:
          Ref: Environment
        ECSCluster:
          Ref: ECSCluster
        PublicSubnetOne:
          Ref: PublicSubnetOne
        PublicSubnetTwo:
          Ref: PublicSubnetTwo
        TaskDefinitionsStackName:
          Ref: TaskDefinitionsStackName
        TaskDefinitionARN:
          Ref: FlaskTaskDefinitionARN
        ServiceDiscoveryARN:
          Ref: FlaskServiceDiscoveryARN
        SecurityGroupId:
          Ref: FlaskSecurityGroupId
  SveltekitService:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/878c12297400556d90442dc824ab08a3.template
      Parameters:
        Environment:
          Ref: Environment
        ECSCluster:
          Ref: ECSCluster
        PublicSubnetOne:
          Ref: PublicSubnetOne
        PublicSubnetTwo:
          Ref: PublicSubnetTwo
        TaskDefinitionARN:
          Ref: SveltekitTakDefinitionARN
        ServiceDiscoveryARN:
          Ref: SveltekitServiceDiscoveryARN
        SecurityGroupId:
          Ref: SveltekitSecurityGroupId
Outputs:
  FlaskServiceArn:
    Value:
      Fn::GetAtt:
      - FlaskService
      - Outputs.ServiceArn
  SveltekitServiceArn:
    Value:
      Fn::GetAtt:
      - SveltekitService
      - Outputs.ServiceArn
