AWSTemplateFormatVersion: '2010-09-09'
Description: Main Task Definitions
Parameters:
  Environment:
    Type: String
  ServiceDiscoveryNamespace:
    Type: String
  ExecutionRoleArn:
    Type: String
  DBSecretArn:
    Type: String
  DBConnectionSecretArn:
    Type: String
Resources:
  NginxTask:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/c52248308c3d950f8730cf8ff6f24461.template
      Parameters:
        Environment:
          Ref: Environment
        ServiceDiscoveryNamespace:
          Ref: ServiceDiscoveryNamespace
        ExecutionRoleArn:
          Ref: ExecutionRoleArn
        TaskCpu: '256'
        TaskMemory: '512'
  FlaskTask:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/c47930f7bfb966a862aee65129372a93.template
      Parameters:
        Environment:
          Ref: Environment
        ExecutionRoleArn:
          Ref: ExecutionRoleArn
        TaskCpu: '256'
        TaskMemory: '512'
        DBSecretArn:
          Ref: DBSecretArn
        DBConnectionSecretArn:
          Ref: DBConnectionSecretArn
  SveltekitTask:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/3c68ae244e5a9942275e542a04860a61.template
      Parameters:
        Environment:
          Ref: Environment
        ExecutionRoleArn:
          Ref: ExecutionRoleArn
        TaskCpu: '1024'
        TaskMemory: '2048'
Outputs:
  NginxTaskDefinitionArn:
    Value:
      Fn::GetAtt:
      - NginxTask
      - Outputs.TaskDefinitionArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-NginxTaskDefArn
  FlaskTaskDefinitionArn:
    Value:
      Fn::GetAtt:
      - FlaskTask
      - Outputs.TaskDefinitionArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-FlaskTaskDefArn
  SvelteTaskDefinitionArn:
    Value:
      Fn::GetAtt:
      - SveltekitTask
      - Outputs.TaskDefinitionArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-SveltekitTaskDefArn
  StackName:
    Description: Stack Name
    Value:
      Ref: AWS::StackName
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-StackName
