AWSTemplateFormatVersion: '2010-09-09'
Description: Nivalta Stack - Main Infrastructure Template
Parameters:
  Environment:
    Type: String
    AllowedValues:
    - prod
    - preprod
    Description: Deployment environment
  ServiceDomainName:
    Type: String
    Description: Base domain name for the application
    Default: nivalta.local
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: Route53 hosted zone ID for domain configuration
  SubDomainPrefix:
    Type: String
    AllowedValues:
    - ''
    - preprod
    Description: Subdomain prefix for environment
  ECSClusterName:
    Type: String
    Description: Name of the ECS Cluster
Resources:
  NivaltaLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName:
        Fn::Sub: /ecs/${Environment}-nivalta
      RetentionInDays: 30
      Tags:
      - Key: Environment
        Value:
          Ref: Environment
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
      - PolicyName: SecretsAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - secretsmanager:GetSecretValue
            Resource:
              Fn::Sub: arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Environment}/nivalta/*
  VPCStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/1d276b868ab8c1d5811ed8fc2d62a5c1.template
      Parameters:
        Environment:
          Ref: Environment
        ServiceDiscoveryDomain:
          Ref: ServiceDomainName
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/9e8183c59df8973536ee14bb1b4ddb6f.template
      Parameters:
        Environment:
          Ref: Environment
        VpcId:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VpcId
  ServiceDiscoveryStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/d9cef04ed9c023d61965e682128fabe4.template
      Parameters:
        Environment:
          Ref: Environment
        VpcId:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VpcId
        ServiceDiscoveryDomain:
          Ref: ServiceDomainName
        DnsRecordTTL: 10
        HealthCheckThreshold: 1
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName:
        Fn::Sub: ${Environment}-nivalta-cluster
      ServiceConnectDefaults:
        Namespace:
          Fn::GetAtt:
          - ServiceDiscoveryStack
          - Outputs.NamespaceName
      CapacityProviders:
      - FARGATE
      - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
      - CapacityProvider: FARGATE
        Weight: 1
      ClusterSettings:
      - Name: containerInsights
        Value: enabled
      Configuration:
        ExecuteCommandConfiguration:
          Logging: OVERRIDE
          LogConfiguration:
            CloudWatchEncryptionEnabled: true
            CloudWatchLogGroupName:
              Fn::Sub: /ecs/${Environment}-nivalta/execute-command
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${Environment}-nivalta-cluster
      - Key: Environment
        Value:
          Ref: Environment
  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    DependsOn:
    - VPCStack
    - SecurityGroupsStack
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/7b0e4c9c89de46b01df1c647d4a138f0.template
      Parameters:
        Environment:
          Ref: Environment
        VpcId:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VpcId
        PublicSubnetOne:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1
        PublicSubnetTwo:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2
        SecurityGroupId:
          Fn::GetAtt:
          - SecurityGroupsStack
          - Outputs.NivaltaLBSecurityGroupId
        DomainName: nivalta.com
        SubDomainPrefix:
          Ref: SubDomainPrefix
        HostedZoneId:
          Ref: HostedZoneId
        HealthCheckPath: /api/version
        HealthCheckInterval: 30
  TasksStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    DependsOn:
    - ServiceDiscoveryStack
    - SecurityGroupsStack
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/a36fd385db06ce0f47ea81c6ce37c728.template
      Parameters:
        ExecutionRoleArn:
          Fn::GetAtt:
          - ECSTaskExecutionRole
          - Arn
        Environment:
          Ref: Environment
        ServiceDiscoveryNamespace:
          Fn::GetAtt:
          - ServiceDiscoveryStack
          - Outputs.NamespaceName
  ServicesStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    DependsOn:
    - VPCStack
    - TasksStack
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/0f01135182c7edde2b0c57b56c9e2d38.template
      Parameters:
        Environment:
          Ref: Environment
        ECSCluster:
          Ref: ECSCluster
        PublicSubnetOne:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1
        PublicSubnetTwo:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2
        TaskDefinitionsStackName:
          Fn::GetAtt:
          - TasksStack
          - Outputs.StackName
        ServiceDiscoveryStackName:
          Fn::GetAtt:
          - ServiceDiscoveryStack
          - Outputs.StackName
        SecurityGroupsStackName:
          Fn::GetAtt:
          - SecurityGroupsStack
          - Outputs.StackName
  NginxServiceStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    DependsOn:
    - ServicesStack
    - LoadBalancerStack
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/nivalta-cloudformation-preprod/ad4680ae3e8923daf47725349ce9de33.template
      Parameters:
        Environment:
          Ref: Environment
        ECSCluster:
          Ref: ECSCluster
        PublicSubnetOne:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1
        PublicSubnetTwo:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2
        TaskDefinitionsStackName:
          Fn::GetAtt:
          - TasksStack
          - Outputs.StackName
        ServiceDiscoveryStackName:
          Fn::GetAtt:
          - ServiceDiscoveryStack
          - Outputs.StackName
        SecurityGroupsStackName:
          Fn::GetAtt:
          - SecurityGroupsStack
          - Outputs.StackName
        LoadBalancerStackName:
          Fn::GetAtt:
          - LoadBalancerStack
          - Outputs.StackName
Outputs:
  LogGroupName:
    Value:
      Ref: NivaltaLogGroup
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-LogGroupName
  TaskExecutionRoleArn:
    Value:
      Fn::GetAtt:
      - ECSTaskExecutionRole
      - Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-TaskExecutionRoleArn
  VPCId:
    Description: VPC ID
    Value:
      Fn::GetAtt:
      - VPCStack
      - Outputs.VpcId
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-VPCId
  LoadBalancerDNS:
    Description: Application Load Balancer DNS
    Value:
      Fn::GetAtt:
      - LoadBalancerStack
      - Outputs.LoadBalancerDNS
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-LoadBalancerDNS
  ServiceEndpoint:
    Description: Service Endpoint URL
    Value:
      Fn::GetAtt:
      - LoadBalancerStack
      - Outputs.DomainEndpoint
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ServiceEndpoint
