name: vector-service

volumes:
  vectordb_vol:
networks:
  vector-network:
    driver: bridge
      
services:
  vector-api:
    container_name: cvector-service
    build:
      context: .
    ports:
    - "5003:5003"
    depends_on:
      - vector-db
    networks:
      - vector-network
    restart: always

  vector-db:
    container_name: cvector-dbase
    image: ankane/pgvector
    ports:
    - "32003:5432"
    environment:
      POSTGRES_DB: vector_db
      POSTGRES_USER: vector_user
      POSTGRES_PASSWORD: vector_pass
    volumes:
      - vectordb_vol:/var/lib/postgresql/data
    networks:
      - vector-network