AWSTemplateFormatVersion: '2010-09-09'
Description: "Main Task Definitions"

Parameters:
  Environment:
    Type: String
  ServiceDiscoveryNamespace:
    Type: String
  ExecutionRoleArn:
    Type: String

Resources:
  NginxTask:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: nginx.yaml
      Parameters:
        Environment: !Ref Environment
        ServiceDiscoveryNamespace: !Ref ServiceDiscoveryNamespace
        ExecutionRoleArn: !Ref ExecutionRoleArn
        TaskCpu: "256"
        TaskMemory: "512"
        # NginxImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/nivalta/nginx-test:latest'

  FlaskTask:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: flask.yaml
      Parameters:
        Environment: !Ref Environment
        ExecutionRoleArn: !Ref ExecutionRoleArn
        TaskCpu: "256"
        TaskMemory: "512"
        # FlaskImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/nivalta/flask-server:latest'
        # DbHost: !ImportValue DatabaseHostName
        # DbName: !Sub nivalta-${Environment}
        # DbSecretArn: !ImportValue DatabaseSecretArn

  SveltekitTask:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: sveltekit.yaml
      Parameters:
        Environment: !Ref Environment
        ExecutionRoleArn: !Ref ExecutionRoleArn
        TaskCpu: "1024"
        TaskMemory: "2048"
        # SveltekitImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/nivalta/sveltekit-server:latest'

Outputs:
  NginxTaskDefinitionArn:
    Value: !GetAtt NginxTask.Outputs.TaskDefinitionArn
    Export:
      Name: !Sub ${AWS::StackName}-NginxTaskDefArn
  FlaskTaskDefinitionArn:
    Value: !GetAtt FlaskTask.Outputs.TaskDefinitionArn
    Export:
      Name: !Sub ${AWS::StackName}-FlaskTaskDefArn
  SvelteTaskDefinitionArn:
    Value: !GetAtt SveltekitTask.Outputs.TaskDefinitionArn
    Export:
      Name: !Sub ${AWS::StackName}-SveltekitTaskDefArn
  StackName:
    Description: Stack Name
    Value: !Ref 'AWS::StackName'
    Export:
      Name: !Sub ${AWS::StackName}-StackName