name: ocr-service

volumes:
  pages_vol:
  ocrdb_vol:
networks:
  ocr-micro-network:
    driver: bridge
      
services:

  local-ocr-db:
    container_name: clocal-ocr-micro-dbase
    image: postgres:15
    ports:
    - "32002:5432" 
    environment:
      POSTGRES_DB: ocr_db
      POSTGRES_USER: local_ocr_user
      POSTGRES_PASSWORD: local_ocr_pass
    volumes:
      - ocrdb_vol:/var/lib/postgresql/data
    networks:
      - ocr-micro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ocr-api:
    container_name: cocr-micro-service
    build:
      context: .
    ports:
    - "5002:5002"
    depends_on:
      local-ocr-db:
        condition: service_healthy
    volumes:
      - .:/usr/src/ocr-service
      - ~/.aws/credentials.tmp:/home/appuser/.aws/credentials
      - pages_vol:/usr/src/ocr-service/pages
    environment:
      - AWS_PROFILE=local-containers
    networks:
      - ocr-micro-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/api/ocr/version"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s