AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nivalta Services Stack'

Parameters:
  Environment:
    Type: String
    AllowedValues: [prod, preprod]

  ECSCluster:
    Type: String
    Description: Name of the ECS Cluster
  
  PublicSubnetOne:
    Type: AWS::EC2::Subnet::Id
  
  PublicSubnetTwo:
    Type: AWS::EC2::Subnet::Id

  TaskDefinitionsStackName:
    Type: String
    Description: Name of the Task Definitions Stack

  FlaskTaskDefinitionARN:
    Type: String

  SveltekitTakDefinitionARN:
    Type: String
  
  FlaskServiceDiscoveryARN:
    Type: String

  SveltekitServiceDiscoveryARN:
    Type: String

  FlaskSecurityGroupId:
    Type: String

  SveltekitSecurityGroupId:
    Type: String

Resources:
  FlaskService:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: flask.yaml
      Parameters:
        Environment: !Ref Environment
        ECSCluster: !Ref ECSCluster
        PublicSubnetOne: !Ref PublicSubnetOne
        PublicSubnetTwo: !Ref PublicSubnetTwo
        TaskDefinitionsStackName: !Ref TaskDefinitionsStackName
        TaskDefinitionARN: !Ref FlaskTaskDefinitionARN
        ServiceDiscoveryARN: !Ref FlaskServiceDiscoveryARN
        SecurityGroupId: !Ref FlaskSecurityGroupId

  SveltekitService:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: sveltekit.yaml
      Parameters:
        Environment: !Ref Environment
        ECSCluster: !Ref ECSCluster
        PublicSubnetOne: !Ref PublicSubnetOne
        PublicSubnetTwo: !Ref PublicSubnetTwo
        TaskDefinitionARN: !Ref SveltekitTakDefinitionARN
        ServiceDiscoveryARN: !Ref SveltekitServiceDiscoveryARN
        SecurityGroupId: !Ref SveltekitSecurityGroupId

Outputs:
  FlaskServiceArn:
    Value: !GetAtt FlaskService.Outputs.ServiceArn
  SveltekitServiceArn:
    Value: !GetAtt SveltekitService.Outputs.ServiceArn