#! bin/bash

PROD=$PROD
HOST=$HOST
PORT=$PORT

if [ $PROD = true ]; then
    echo "Building for production"
    npm run build
else
    echo "No Build Required"
fi

adduser -D reactuser && chown -R reactuser /usr/src/react

if [ $PROD = true ]; then
    echo "Starting Production Grade React"
    node build
else
    echo "Starting Dev Grade React"
    npm run dev -- --host $HOST --port $PORT
fi
