"""add symptom table

Revision ID: a3fd4c4ea167
Revises: 2893ee8db718
Create Date: 2024-09-26 14:23:04.369017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fd4c4ea167'
down_revision = '2893ee8db718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptoms',
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('symptom_name', sa.String(length=50), nullable=False),
    sa.Column('symptom_description', sa.String(length=255), nullable=False),
    sa.Column('symptom_duration', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('symptom_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptoms')
    # ### end Alembic commands ###
