#!/bin/bash

delete-stack() {
  local stack_name=$1
  aws cloudformation delete-stack --stack-name "$stack_name" && aws cloudformation wait stack-delete-complete --stack-name "$stack_name"
}

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <stack-name>"
  exit 1
fi

delete-stack "$1"
