#!/bin/bash

# Get the local machine's IP address
LOCAL_IP=$(curl -s https://checkip.amazonaws.com)
SECURITY_GROUP='sg-0cdea797bd3fd047a'

DB_RULE_UPDATE='{
    "IpProtocol": "tcp",
    "FromPort": 3306,
    "ToPort": 3306,
    "CidrIpv4": "'"$LOCAL_IP"'/32",
    "Description": "Allow DB traffic"
}'

aws ec2 modify-security-group-rules \
    --group-id $SECURITY_GROUP \
    --security-group-rules '[{
        "SecurityGroupRuleId": "sgr-024e7ff2a6d500f92",
        "SecurityGroupRule": '"$DB_RULE_UPDATE"'
    }]'
