name: vector-service

volumes:
  vectordb_vol:
networks:
  vector-network:
    driver: bridge
      
services:
  vector-api:
    container_name: cvector-service
    build:
      context: .
    ports:
    - "5003:5003"
    depends_on:
      local-vector-db:
        condition: service_healthy
    networks:
      - vector-network
    restart: always

  local-vector-db:
    container_name: cvector-dbase
    image: ankane/pgvector
    ports:
    - "32003:5432"
    environment:
      POSTGRES_DB: local_vector_db
      POSTGRES_USER: local_vector_user
      POSTGRES_PASSWORD: local_vector_pass
    volumes:
      - vectordb_vol:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vector-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5