name: Prune Stale branches

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete Stale Branches
        run: |
          git fetch --prune
          git branch --merged origin/main | grep -v 'main$' | xargs -r git branch -d